version: '3'

networks:
  traefik-net:
    external: true
  local:

services:
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: feip
      MINIO_ROOT_PASSWORD: minio_password
      MINIO_BROWSER_REDIRECT_URL: https://minio_console.mrfox131.ru
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio_console.rule=Host(`minio_console.mrfox131.ru`)"
      - "traefik.http.routers.minio_console.entrypoints=websecure"
      - "traefik.http.routers.minio_console.tls=true"
      - "traefik.http.routers.minio_console.tls.certresolver=le"
      - "traefik.http.routers.minio_console.service=minio_console"
      - "traefik.http.services.minio_console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio_api.rule=Host(`s3.mrfox131.ru`)"
      - "traefik.http.routers.minio_api.entrypoints=websecure"
      - "traefik.http.routers.minio_api.tls=true"
      - "traefik.http.routers.minio_api.tls.certresolver=le"
      - "traefik.http.routers.minio_api.service=minio_api"
      - "traefik.http.services.minio_api.loadbalancer.server.port=9000"
    networks:
      - local
      - traefik-net
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: feip
      POSTGRES_DB: feip
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - PGDATA_FEIP:/var/lib/postgresql/data/pgdata
    networks:
      - local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "feip" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
  
  service_db_init:
    build: .
    entrypoint: alembic upgrade head
    networks: 
      - local
    environment:
      DB_USERNAME: feip
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_DATABASE: feip
  service:
    build: .
    depends_on:
      service_db_init:
        condition: service_completed_successfully
    networks: 
      - local
      - traefik-net
    environment:
      DB_USERNAME: feip
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_DATABASE: feip
    restart: always
    expose:
      - 80    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.mrfox131.ru`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
volumes:
  PGDATA_FEIP:
  minio-storage: