version: '3'

networks:
  traefik-net:
    external: true
  local:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: feip
      POSTGRES_DB: feip
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "feip" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
  
  service_db_init:
    build: .
    entrypoint: alembic upgrade head
    networks: 
      - local
    environment:
      DB_USERNAME: feip
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_DATABASE: feip
  service:
    build: .
    depends_on:
      service_db_init:
        condition: service_completed_successfully
    networks: 
      - local
      - traefik-net
    environment:
      DB_USERNAME: feip
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_DATABASE: feip
    restart: always
    expose:
      - 80    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.mrfox131.ru`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
      