version: '3'

networks:
  traefik-net:
    external: true
  local:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: feip
      POSTGRES_DB: feip
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "feip" ]
      interval: 30s
      timeout: 60s
      retries: 5
  
  service_db_init:
    build: .
    entrypoint: alembic upgrade head
    networks: 
      - local
    environment:
      db_username: feip
      db_password: ${POSTGRES_PASSWORD}
      db_host: feip
  service:
    build: .
    depends_on:
      service_db_init:
        condition: service_completed_successfully
    networks: 
      - local
  
      