"""Added fk to photos

Revision ID: 26332a29bc04
Revises: aaf1096180aa
Create Date: 2023-06-20 22:27:52.610291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26332a29bc04'
down_revision = 'aaf1096180aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goodphoto', sa.Column('good_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'goodphoto', 'good', ['good_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goodphoto', type_='foreignkey')
    op.drop_column('goodphoto', 'good_id')
    # ### end Alembic commands ###
