"""Added delete cascade

Revision ID: 5a7b39e7522c
Revises: 241efec4b6c9
Create Date: 2023-06-22 21:39:47.097607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7b39e7522c'
down_revision = '241efec4b6c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_good_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'good', ['good_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('goodphoto_good_id_fkey', 'goodphoto', type_='foreignkey')
    op.create_foreign_key(None, 'goodphoto', 'good', ['good_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goodphoto', type_='foreignkey')
    op.create_foreign_key('goodphoto_good_id_fkey', 'goodphoto', 'good', ['good_id'], ['id'])
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_good_id_fkey', 'cart', 'good', ['good_id'], ['id'])
    # ### end Alembic commands ###
