"""goods tables

Revision ID: 61c4ef8427d9
Revises: 6cb219725c08
Create Date: 2023-06-18 12:53:25.999643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61c4ef8427d9"
down_revision = "6cb219725c08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "color",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "good",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("color_id", sa.UUID(), nullable=True),
        sa.Column("cost", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sale",
        sa.Column("good_id", sa.UUID(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["good_id"],
            ["good.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "size",
        sa.Column("good_id", sa.UUID(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["good_id"],
            ["good.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("good_id", "size"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("size")
    op.drop_table("sale")
    op.drop_table("good")
    op.drop_table("color")
    op.drop_table("category")
    op.drop_table("brand")
    # ### end Alembic commands ###
