"""Changed size to be int

Revision ID: 73764176e1f0
Revises: 0cbe8ef96e5e
Create Date: 2023-06-22 17:55:01.053283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73764176e1f0'
down_revision = '0cbe8ef96e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("size", "size")
    op.add_column("size", sa.Column("size", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
