"""Added remainder to Good

Revision ID: 82b8f64c822a
Revises: 61c4ef8427d9
Create Date: 2023-06-18 12:57:32.344649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b8f64c822a'
down_revision = '61c4ef8427d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('remainder', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'remainder')
    # ### end Alembic commands ###
