"""Added photos for goods

Revision ID: aaf1096180aa
Revises: c40bd5ca2d0f
Create Date: 2023-06-20 22:21:29.004036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf1096180aa'
down_revision = 'c40bd5ca2d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodphoto',
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goodphoto')
    # ### end Alembic commands ###
