"""Moved remainder, added created_at, updated_at

Revision ID: c40bd5ca2d0f
Revises: 82b8f64c822a
Create Date: 2023-06-18 13:06:18.694899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c40bd5ca2d0f"
down_revision = "82b8f64c822a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "good",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "good",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("good", "remainder")
    op.add_column("sale", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column(
        "sale",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "sale",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("size", sa.Column("remainder", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("size", "remainder")
    op.drop_column("sale", "updated_at")
    op.drop_column("sale", "created_at")
    op.drop_column("sale", "active")
    op.add_column(
        "good",
        sa.Column("remainder", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("good", "updated_at")
    op.drop_column("good", "created_at")
    # ### end Alembic commands ###
